
name: Update index.js file
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run update file script
      run: python ./updatefile.py
    - name: Commit and push
      uses: test-room-7/action-update-file@v1.1.0
      with:
        commit-msg: "Auto update index.js"
        file-path: "api/GetMessage/index.js"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Trigger workflow
      run: |
        $uri = "https://api.github.com/repos/StaticWebAppTest/vanilla-api-westus2/actions/workflows//azure-static-web-apps-ashy-hill-0339df41e.yml/dispatches" 
        $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
        $headers.Add("Authorization", "Bearer ${{secrets.WORKFLOW_PAT}}")
        $headers.Add("Accept", "application/vnd.github.everest-preview+json")
        $headers.Add("Content-Type", "application/json")

        $response = Invoke-RestMethod -Uri $uri -Headers $headers -Body $body -Method POST
        $response | ConvertTo-Json