
name: AutoUpdateFile
on:
  schedule:
  - cron: "*/60 * * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run update file script
      run: python ./updatefile.py
    - name: Commit and push
      uses: test-room-7/action-update-file@v1.1.0
      with:
        commit-msg: "Auto update index.js"
        file-path: "api/GetMessage/index.js"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    
